import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PEOPLE,baseState,newAttempt,numeric,summary,interactions,latestInteractions,insights,createTicket,readyTicket,gates,canStage,canRelease,bumpRevision} from '../dist/domain.js';
const [advanced,basic]=JSON.parse(readFileSync(new URL('../dist/samples/catalog.json',import.meta.url)));
test('empty state never invents results',()=>{assert.equal(baseState().attempts.length,0);assert.equal(summary(null,advanced).score,null);assert.equal(insights(null,advanced)[0].kind,'info');assert.deepEqual(interactions(null),[]);for(const v of [undefined,'','NaN','x'])assert.equal(numeric(v),null);assert.equal(numeric('0'),0)});
test('independent attempts use correct SCORM vocabularies and objectives',()=>{const a=newAttempt(advanced,PEOPLE[0]),b=newAttempt(basic,PEOPLE[1]);assert.notEqual(a.id,b.id);assert.equal(a.data['cmi.learner_id'],'noa');assert.equal(b.data['cmi.core.student_id'],'omar');assert.equal(a.data['cmi.objectives.1.id'],'obj_etiquette');assert.equal(summary(a,advanced).status,'active');assert.equal(summary(b,basic).success,'unknown');assert.equal(newAttempt({...basic,objectives:undefined},PEOPLE[0]).sessions,0)});
test('completion is distinct from score and pass',()=>{const a=newAttempt(advanced,PEOPLE[0]);a.data['cmi.completion_status']='completed';assert.equal(summary(a,advanced).score,null);assert.equal(insights(a,advanced).at(-1).title,'השלמה אינה ציון');a.data['cmi.score.raw']='80';a.data['cmi.score.scaled']='0.8';assert.equal(summary(a,advanced).success,'passed');assert.equal(summary(a,advanced).derived,true);a.data['cmi.score.scaled']='0.79';assert.equal(summary(a,advanced).success,'failed');a.data['cmi.success_status']='passed';assert.equal(summary(a,advanced).derived,false);const b=newAttempt(basic,PEOPLE[0]);b.data['cmi.core.lesson_status']='failed';b.data['cmi.core.score.raw']='60';assert.equal(summary(b,basic).success,'failed');assert.equal(insights(b,basic)[0].title,'הלומדה מדווחת תוצאה כללית בלבד')});
function question(a,i,id,result,objective){Object.assign(a.data,{[`cmi.interactions.${i}.id`]:id,[`cmi.interactions.${i}.description`]:'Question '+id,[`cmi.interactions.${i}.learner_response`]:'A',[`cmi.interactions.${i}.correct_responses.0.pattern`]:'B',[`cmi.interactions.${i}.result`]:result,[`cmi.interactions.${i}.objectives.0.id`]:objective,[`cmi.interactions.${i}.type`]:'choice'})}
test('reports use latest answer, preserve raw history and group evidence',()=>{const a=newAttempt(advanced,PEOPLE[0]);question(a,0,'q1','incorrect','obj_playing');question(a,1,'q2','wrong','obj_etiquette');question(a,2,'q1','correct','obj_playing');assert.equal(interactions(a).length,3);assert.equal(latestInteractions(a).length,2);assert.equal(summary(a,advanced).correct,1);assert.equal(summary(a,advanced).wrong,1);assert.equal(insights(a,advanced)[0].objective,'obj_etiquette');question(a,3,'q2','correct','obj_etiquette');assert.equal(insights(a,advanced)[0].kind,'good');question(a,4,'q3','incorrect','custom');assert.match(insights(a,advanced)[0].title,/השאלות/);question(a,5,'q4','incorrect','');assert.ok(insights(a,advanced).length>=1);a.data={'cmi.interactions.0.id':'legacy','cmi.interactions.0.student_response':'c'};assert.equal(interactions(a)[0].response,'c');assert.equal(interactions(a)[0].result,'unknown')});
const complete=()=>({...createTicket(),title:'Resume',description:'Save bookmark',acceptance:'Resume same page',autoPlan:'Roundtrip and errors',manualPlan:'Run course',status:'development'});
test('no task cannot pass quality gates',()=>{assert.equal(readyTicket(null),false);assert.equal(readyTicket(createTicket(2)),false);assert.equal(canStage(null),false);assert.equal(canRelease(null),false);assert.deepEqual(gates(null),[])});
test('every quality gate applies to current code revision',()=>{const t=complete();assert.equal(readyTicket(t),true);assert.equal(canStage(t),false);Object.assign(t,{review:'approved',reviewRevision:1,peer:true,peerRevision:1,tests:'passed',testsRevision:1,coverage:{frontend:{lines:90,branches:90,functions:90},server:{lines:90,branches:90,functions:90}}});assert.equal(canStage(t),true);assert.equal(canRelease(t),false);t.coverage.frontend.branches=89;assert.equal(canStage(t),false);t.coverage.frontend.branches=90;t.coverage.server.functions=NaN;assert.equal(canStage(t),false);t.coverage.server.functions=90;t.stagedRevision=1;t.manual='passed';t.manualRevision=1;t.releaseApproval=true;assert.equal(canRelease(t),true);t.reviewRevision=0;assert.equal(canStage(t),false);t.reviewRevision=1;bumpRevision(t);assert.equal(t.revision,2);assert.equal(canRelease(t),false);assert.equal(t.coverage,null);assert.equal(t.releaseApproval,false)});
test('embedded content never invents question insights',()=>{assert.match(insights({data:{}},{kind:'external'})[0].title,/ללא דיווח/);assert.equal(numeric(null),null)});
